# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Mount Data
email: info@themountdata.com
description: >- # this means to ignore newlines until "baseurl:"
  Creemos en los datos, la tecnología y el análisis para marketing y ventas
# baseurl: "/themountdata" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://themountdata.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: themountdata
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Multilingual references
# https://www.sylvaindurand.org/making-jekyll-multilingual/
# Indicate, for each post and page, its language (lang) and an unique identifier
# to link the different translations
#
# 404 (no encontrada)
r_404:
  es: 404.html
  ca: ca/404.html
  en: en/404.html
# Home
r_index:
  es:
  ca: ca/
  en: en/
# Nosotros
r_nosotros:
  es: nosotros/
  ca: ca/nosaltres/
  en: en/about/
# Servicios
r_servicios:
  es: servicios/
  ca: ca/serveis/
  en: en/services/
r_servicios_accion:
  es: servicios/accion/
  ca: ca/serveis/accio/
  en: en/services/action/
r_servicios_analisis:
  es: servicios/analisis/
  ca: ca/serveis/analisi/
  en: en/services/analysis/
r_servicios_datos:
  es: servicios/datos/
  ca: ca/serveis/dades/
  en: en/services/data/
r_servicios_visualizacion:
  es: servicios/visualizacion/
  ca: ca/serveis/visualitzacio/
  en: en/services/visualization/
# Soluciones
r_soluciones:
  es: soluciones/
  ca: ca/solucions/
  en: en/solutions/
r_soluciones_sherpa_campaign:
  es: soluciones/sherpa-campaign/
  ca: ca/solucions/sherpa-campaign/
  en: en/solutions/sherpa-campaign/
r_soluciones_sherpa_dashboard:
  es: soluciones/sherpa-dashboard/
  ca: ca/solucions/sherpa-dashboard/
  en: en/solutions/sherpa-dashboard/

# Translation
# Common elements
t_footer_legal:
  es:
    privacy: Privacidad
    cookies: Cookies
    terms: Aviso legal
  ca:
    privacy: Privacitat
    cookies: Cookies
    terms: Avís legal
  en:
    privacy: Privacy
    cookies: Cookies
    terms: Terms
t_footer:
  es:
    location: Ubicación
    contact: Contactar
  ca:
    location: Ubicació
    contact: Contactar
  en:
    location: Location
    contact: Contact
